# 此为安装R包的文件
# package pathway
.libPaths()
file.edit("~/.Rprofile")

# 原生安装########
install.packages("randomForest")
install.packages("ranger")
install.packages("MLmetrics")
install.packages("lightgbm")
install.packages("Ckmeans.1d.dp")
install.packages("proj4")
install.packages("clustermole")
install.packages("forestploter")
install.packages('ggfortify')
install.packages("gptstudio")
install.packages("BiocManager")
install.packages("slider")
install.packages("matrixStats")
install.packages("Hmisc")
install.packages("splines")
install.packages( "foreach")
install.packages( "doParallel")
install.packages( "reshape")
install.packages( "fastcluster")
install.packages( "dynamicTreeCut")
install.packages( "survival")
install.packages("scatterplot3d")
install.packages("devtools")
install.packages("scatterplot3d")
install.packages("ndl")
install.packages("glmnet")
install.packages("ggstatsplot")
install.packages("afex")
install.packages('PMCMRplus')
install.packages("ggExtra")
install.packages('ComplexUpset')
install.packages("calendR")
install.packages("mosaic")
install.packages("profvis")
install.packages('faraway')
install.packages("RcppEigen")
install.packages("jpeg")
install.packages("mvtnorm")
install.packages("numDeriv")
install.packages("magick")
install.packages("DT")
install.packages("pheatmap")
install.packages("scatterplot3d")
install.packages("languageserver")
install.packages("mosaic")
options(repos=c(getOption("repos"), "https://ccb.nki.nl/software/discover/repos/r"))
install.packages("discover")
install.packages("ggside")
install.packages("dlstats")
install.packages("meme")
install.packages("wrapr")
install.packages("vroom")
# BiocManager#######
if (!require("BiocManager", quietly = TRUE))
  install.packages("BiocManager")
BiocManager::install(version = "3.18")# 这一行需要去官网随时更新。要不然有些包安装不上。

BiocManager::install("", update = FALSE)
BiocManager::install("", update = FALSE)
BiocManager::install("binom", update = FALSE)
BiocManager::install("CellBench", update = FALSE)
BiocManager::install("speckle", update = FALSE)
BiocManager::install("mvnmle", update = FALSE)
BiocManager::install("tableone", update = FALSE)
BiocManager::install("misty", update = FALSE)
BiocManager::install("jokergoo/ComplexHeatmap", update = FALSE)
BiocManager::install("grisslab/scAnnotatR", update = FALSE)
BiocManager::install("questionr", update = FALSE)
BiocManager::install("srvyr", update = FALSE)
BiocManager::install("survey", update = FALSE)
BiocManager::install("celldex", update = FALSE)
BiocManager::install("herdiantrisufriyana/rmlnomogram", update = FALSE)
BiocManager::install("tidymodels/probably", update = FALSE)
BiocManager::install("HEMDAG", update = FALSE)
BiocManager::install("PerfMeas", update = FALSE)
BiocManager::install("waffle", update = FALSE)
BiocManager::install("dcurves", update = FALSE)
BiocManager::install("ModelOriented/kernelshap", update = FALSE)
BiocManager::install("fastshap", update = FALSE)
BiocManager::install("cvAUC", update = FALSE)
BiocManager::install("RWeka", update = FALSE)
BiocManager::install("prioritylasso", update = FALSE)
BiocManager::install("nycflights13", update = FALSE)
BiocManager::install("mlr3db", update = FALSE)
BiocManager::install("localModel", update = FALSE)
BiocManager::install("lime", update = FALSE)
BiocManager::install("shapviz", update = FALSE)
BiocManager::install("kernelshap", update = FALSE)
BiocManager::install("OpenML", update = FALSE)
BiocManager::install("mlr-org/paradox", update = FALSE)
BiocManager::install("naniar", update = FALSE)
BiocManager::install("mlr3oml", update = FALSE)
BiocManager::install("FSelectorRcpp", update = FALSE)
BiocManager::install("survivalmodels", update = FALSE)
BiocManager::install("dbscan", update = FALSE)
BiocManager::install("mlr3benchmark", update = FALSE)
BiocManager::install("rmdformats", update = FALSE)
BiocManager::install("kknn", update = FALSE)
BiocManager::install("h2o", update = FALSE)
BiocManager::install("msm", update = FALSE)
BiocManager::install("eoffice", update = FALSE)
BiocManager::install("jskm", update = FALSE)
BiocManager::install("adjustedCurves", update = FALSE)
BiocManager::install("ggsurvfit", update = FALSE)
BiocManager::install("StepReg", update = FALSE)
BiocManager::install("tidyfst", update = FALSE)
BiocManager::install("chest", update = FALSE)
BiocManager::install("rcssci", update = FALSE)
BiocManager::install("ggrcs", update = FALSE)
BiocManager::install("OptimalCutpoints", update = FALSE)
BiocManager::install("CatPredi", update = FALSE)
BiocManager::install("reportROC", update = FALSE)
BiocManager::install("autoReg", update = FALSE)
BiocManager::install("rrtable", update = FALSE)
BiocManager::install("forestmodel", update = FALSE)
BiocManager::install("jstable", update = FALSE)
BiocManager::install("dagitty", update = FALSE)
BiocManager::install("broom.helpers", update = FALSE)
BiocManager::install("broom.mixed", update = FALSE)
BiocManager::install("tidycmprsk", update = FALSE)
BiocManager::install("glue", update = FALSE)
BiocManager::install("tableone", update = FALSE)
BiocManager::install("compareGroups", update = FALSE)
BiocManager::install("", update = FALSE)
BiocManager::install("CBCgrps", update = FALSE)
BiocManager::install("gtsummary", update = FALSE)
BiocManager::install("gt", update = FALSE)
BiocManager::install("finalfit", update = FALSE)
BiocManager::install("ggmap", update = FALSE)
BiocManager::install("DALEXtra", update = FALSE)
BiocManager::install("DALEX", update = FALSE)
BiocManager::install("iml", update = FALSE)
BiocManager::install("praznik", update = FALSE)
BiocManager::install("rpart.plot", update = FALSE)
BiocManager::install("precrec", update = FALSE)
BiocManager::install("mlr3verse", update = FALSE)
BiocManager::install("mlr3viz", update = FALSE)
BiocManager::install("caret", update = FALSE)
BiocManager::install("tidymodels", update = FALSE)
BiocManager::install("mlr3", update = FALSE)
BiocManager::install("survivalsvm", update = FALSE)
BiocManager::install("BART", update = FALSE)
BiocManager::install("compareC", update = FALSE)
BiocManager::install("superpc", update = FALSE)
BiocManager::install("plsRcox", update = FALSE)
BiocManager::install("mice", update = FALSE)
BiocManager::install("patchwork", update = FALSE)
BiocManager::install("geneset", update = FALSE)
BiocManager::install("ReactomePA", update = FALSE)
BiocManager::install("genekitr", update = FALSE)
BiocManager::install("PREDA", update = FALSE) #https://www.mdpi.com/2896194
BiocManager::install("Damirseq", update = FALSE) # 另外一个去除批次效应的工具？https://www.mdpi.com/2896194
BiocManager::install("gggenes", update = FALSE)
BiocManager::install("gwasrapidd", update = FALSE)
BiocManager::install("archive", update = FALSE)
BiocManager::install("SNPlocs.Hsapiens.dbSNP151.GRCh38", update = FALSE)
BiocManager::install("MungeSumstats", update = FALSE)
BiocManager::install("SNPlocs.Hsapiens.dbSNP155.GRCh38", update = FALSE)
BiocManager::install("Nebulosa", update = FALSE)
BiocManager::install("scCustomize", update = FALSE)
BiocManager::install("DAAG", update = FALSE)
BiocManager::install("extremevalues", update = FALSE)
BiocManager::install("tidydr", update = FALSE)
BiocManager::install("EnrichmentBrowser", update = FALSE)
BiocManager::install("scRNAseq", update = FALSE)
BiocManager::install("HGNChelper", update = FALSE)
BiocManager::install("alabaster.schemas", update = FALSE)
BiocManager::install("celldex", update = FALSE)
BiocManager::install("SNPlocs.Hsapiens.dbSNP144.GRCh37", update = FALSE)
BiocManager::install("BSgenome", update = FALSE)
BiocManager::install("mlbench", update = FALSE)
BiocManager::install("forestploter", update = FALSE)
BiocManager::install("vcfR", update = FALSE)
BiocManager::install("RcppAlgos", update = FALSE)
BiocManager::install("arrow", update = FALSE)
BiocManager::install("RcisTarget", update = FALSE)
BiocManager::install("ggiraph", update = FALSE)
BiocManager::install("ggiraphExtra", update = FALSE)
BiocManager::install("devtools", update = FALSE)
BiocManager::install("DelayedArray", update = FALSE)
BiocManager::install("clustermole", update = FALSE)
BiocManager::install("threejs", update = FALSE)
BiocManager::install("batchelor", update = FALSE)
BiocManager::install("DelayedArray", update = FALSE)
BiocManager::install("DelayedMatrixStats", update = FALSE)
BiocManager::install("terra", update = FALSE)
BiocManager::install("glmGamPoi", update = FALSE)
BiocManager::install("doMC", update = FALSE)
BiocManager::install("R2HTML", update = FALSE)
BiocManager::install("rbokeh", update = FALSE)
BiocManager::install("R.matlab", update = FALSE)
BiocManager::install("matlabr", update = FALSE)
BiocManager::install("MAST", update = FALSE)
BiocManager::install("SingleR", update = FALSE)
BiocManager::install("JASPAR2022",update = FALSE)
BiocManager::install("TFBSTools",update = FALSE)
BiocManager::install("BSgenome.Hsapiens.UCSC.hg38",update = FALSE)
BiocManager::install("pillar",update = FALSE)
BiocManager::install("pkgconfig",update = FALSE)
BiocManager::install("easypackages",update = FALSE)
BiocManager::install("tidyverse",update = FALSE)
BiocManager::install("survival",update = FALSE)
BiocManager::install("limma",update = FALSE)
BiocManager::install("ggalluvial",update = FALSE)
BiocManager::install("pheatmap",update = FALSE)
BiocManager::install("edgeR",update = FALSE)
BiocManager::install("AnnotationHub",update = FALSE)
BiocManager::install("GenomicDataCommons",update = FALSE)
BiocManager::install("TCGAbiolinks",update = FALSE)
BiocManager::install("remotes",update = FALSE)
BiocManager::install("BioinformaticsFMRP/TCGAbiolinksGUI.data",update = FALSE)
BiocManager::install("BioinformaticsFMRP/TCGAbiolinks",update = FALSE)
BiocManager::install("sva",update = FALSE)
BiocManager::install("data.table",update = FALSE,force = TRUE)
BiocManager::install("rtracklayer",update = FALSE)
BiocManager::install("SummarizedExperiment",update = FALSE)
BiocManager::install("WGCNA",update = FALSE)
BiocManager::install("GEOquery",update = FALSE)
BiocManager::install("choose.dir",update = FALSE)
BiocManager::install("affy",update = FALSE)
BiocManager::install("hgu133plus2cdf",update = FALSE)
BiocManager::install("hgu133plus2.db",update = FALSE)
BiocManager::install("arrayQualityMetrics",update = FALSE)
BiocManager::install("statmod",update = FALSE)
BiocManager::install("gProfileR", update = FALSE)
BiocManager::install(c("GO.db", "preprocessCore", "impute"), update = FALSE)
BiocManager::install("gprofiler2", update = FALSE)
BiocManager::install("airway", update = FALSE)
BiocManager::install("DESeq2", update = FALSE)
BiocManager::install("ridittools", update = FALSE)
BiocManager::install("Ridit", update = FALSE)
BiocManager::install("DHARMa", update = FALSE)
BiocManager::install("pscl", update = FALSE)
BiocManager::install("robust", update = FALSE)
BiocManager::install("qcc", update = FALSE)
BiocManager::install("effects", update = FALSE)
BiocManager::install("MPV", update = FALSE)
BiocManager::install("ridge", update = FALSE)
BiocManager::install("insight", update = FALSE)
BiocManager::install("parameters", update = FALSE)
BiocManager::install("effectsize", update = FALSE)
BiocManager::install("sjPlot", update = FALSE)
BiocManager::install("MCMCpack", update = FALSE)
BiocManager::install("av", update = FALSE)
BiocManager::install("survminer", update = FALSE)
BiocManager::install("RISmed", update = FALSE)
BiocManager::install("attempt", update = FALSE)
BiocManager::install("quanteda", update = FALSE)
BiocManager::install("splitstackshape", update = FALSE)
BiocManager::install("mayo", update = FALSE)
BiocManager::install("timeROC", update = FALSE)
BiocManager::install("modelROC", update = FALSE)
BiocManager::install("ggDCA", update = FALSE)
BiocManager::install("ggeasy", update = FALSE)
BiocManager::install("table1", update = FALSE)
BiocManager::install("rsconnect", update = FALSE)
BiocManager::install("packrat", update = FALSE)
BiocManager::install("forestplot", update = FALSE)
BiocManager::install("predtools", update = FALSE)
BiocManager::install("gbm", update = FALSE)
BiocManager::install("DynNom", update = FALSE)
BiocManager::install("TSA", update = FALSE)
BiocManager::install("fpp", update = FALSE)
BiocManager::install("maftools", update = FALSE)
BiocManager::install("wesanderson", update = FALSE)
BiocManager::install("RCy3", update = FALSE)
BiocManager::install("survivalAnalysis", update = FALSE)
BiocManager::install("tidytidbits", update = FALSE)
BiocManager::install("DescTools", update = FALSE)
BiocManager::install("PropCIs", update = FALSE)
BiocManager::install("pwr", update = FALSE)
BiocManager::install("rcompanion", update = FALSE)
BiocManager::install("vcdExtra", update = FALSE)
BiocManager::install("umap", update = FALSE)
BiocManager::install("Cairo", update = FALSE)
BiocManager::install("circlize", update = FALSE)
BiocManager::install("dendextend", update = FALSE)
BiocManager::install("ggcorrplot", update = FALSE)
BiocManager::install("gghighlight", update = FALSE)
BiocManager::install("ggnewscale", update = FALSE)
BiocManager::install("ggseqlogo", update = FALSE)
BiocManager::install("ggtern", update = FALSE)
BiocManager::install("ggthemes", update = FALSE)
BiocManager::install("ggupset", update = FALSE)
BiocManager::install("rgdal", update = FALSE)
BiocManager::install("seqinr", update = FALSE)
BiocManager::install("treemapify", update = FALSE)
BiocManager::install("VennDiagram", update = FALSE)
BiocManager::install("clustree", update = FALSE)
BiocManager::install("Seurat", update = FALSE) # 目前的版本为> packageVersion("Seurat")  '4.4.0'
BiocManager::install("xlsx", update = FALSE)
BiocManager::install("PerformanceAnalytics", update = FALSE)
BiocManager::install("RNHANES", update = FALSE)
BiocManager::install("ggbreak", update = FALSE)
BiocManager::install("ggh4x", update = FALSE)
BiocManager::install("gg.gap", update = FALSE)
BiocManager::install("PredictABEL", update = FALSE)
BiocManager::install("collapse", update = FALSE)
BiocManager::install("caret", update = FALSE)
BiocManager::install("rlang", update = FALSE,force = TRUE)
BiocManager::install("palmerpenguins", update = FALSE)
BiocManager::install("rgdal", update = FALSE)
BiocManager::install("countToFPKM", update = FALSE)
BiocManager::install("GenomicFeatures", update = FALSE)
BiocManager::install("CircStats", update = FALSE)
BiocManager::install("GAD", update = FALSE)
BiocManager::install("tximport", update = FALSE)
BiocManager::install("tximportData", update = FALSE)
BiocManager::install("tidyHeatmap", update = FALSE)
BiocManager::install("httr", update = FALSE)
BiocManager::install("RCurl", update = FALSE)
BiocManager::install("rjson", update = FALSE)
BiocManager::install("rgl", update = FALSE)
BiocManager::install("RColorBrewer", update = FALSE)
BiocManager::install("colorspace", update = FALSE)
BiocManager::install("rms", update = FALSE)
BiocManager::install("foreign", update = FALSE)
BiocManager::install("regplot", update = FALSE)
BiocManager::install("mstate", update = FALSE)
BiocManager::install("grid", update = FALSE)
BiocManager::install("lattice", update = FALSE)
BiocManager::install("Formula", update = FALSE)
BiocManager::install("rmda", update = FALSE)
BiocManager::install("openxlsx", update = FALSE)
BiocManager::install("e1071", update = FALSE)
BiocManager::install("biomaRt", update = FALSE)
BiocManager::install("org.Hs.eg.db", update = FALSE)
BiocManager::install("enrichplot", update = FALSE)
BiocManager::install("survcomp", update = FALSE)
BiocManager::install("preprocessCore", update = FALSE)
BiocManager::install("ArrayExpress", update = FALSE)
BiocManager::install("EBSeq", update = FALSE)
BiocManager::install("RRHO", update = FALSE)
BiocManager::install("showtext", update = FALSE)
BiocManager::install("randomForest", update = FALSE)
BiocManager::install("ISLR", update = FALSE)
BiocManager::install("BSDA", update = FALSE)
BiocManager::install("RVAideMemoire", update = FALSE)
BiocManager::install("ConsensusClusterPlus", update = FALSE,force = TRUE)
BiocManager::install("NMF", update = FALSE)
BiocManager::install("clusterRepro", update = FALSE)
BiocManager::install("GGally", update = FALSE)
BiocManager::install("psych", update = FALSE)
BiocManager::install("ips", update = FALSE)
BiocManager::install("hrbrthemes", update = FALSE)
BiocManager::install("afex", update = FALSE)
BiocManager::install("esquisse", update = FALSE)
BiocManager::install("gapminder", update = FALSE)
BiocManager::install("gcookbook", update = FALSE)
BiocManager::install("gganimate", update = FALSE)
BiocManager::install("ggExtra", update = FALSE)
BiocManager::install("ggstatsplot", update = FALSE)
BiocManager::install("paletteer", update = FALSE)
BiocManager::install("caTools", update = FALSE)
BiocManager::install("heatmaply", update = FALSE)
BiocManager::install("msigdbr", update = FALSE)
BiocManager::install("GSVA", update = FALSE)
BiocManager::install("sigFeature", update = FALSE)
BiocManager::install("Gviz", update = FALSE)
BiocManager::install("english", update = FALSE)
BiocManager::install("GOplot", update = FALSE)
BiocManager::install("org.Mm.eg.db", update = FALSE)
BiocManager::install("randomForestSRC", update = FALSE)
BiocManager::install("survRM2", update = FALSE)
BiocManager::install("ComparisonSurv", update = FALSE)
BiocManager::install("Boruta", update = FALSE)
BiocManager::install("gcrma", update = FALSE)
BiocManager::install("microbenchmark", update = FALSE)
BiocManager::install("ppcor", update = FALSE)
BiocManager::install("pacman", update = FALSE)
BiocManager::install("Rmisc", update = FALSE)
BiocManager::install("Cairo", update = FALSE)
BiocManager::install("SimDesign", update = FALSE)
BiocManager::install("tdROC", update = FALSE)
BiocManager::install("strucchange", update = FALSE)
BiocManager::install("mRMRe", update = FALSE)
BiocManager::install("miRBaseVersions.db", update = FALSE)
BiocManager::install("miRBaseConverter", update = FALSE)
BiocManager::install("givitiR", update = FALSE)
BiocManager::install("ResourceSelection", update = FALSE)
BiocManager::install("EnvStats", update = FALSE)
BiocManager::install("matlab", update = FALSE)
BiocManager::install("ClassDiscovery", update = FALSE)
BiocManager::install("smoothHR", update = FALSE)
BiocManager::install("RCircos", update = FALSE)
BiocManager::install("cmapR", update = FALSE)
BiocManager::install("EDASeq", update = FALSE)
BiocManager::install("karyoploteR", update = FALSE)
BiocManager::install("httpgd", update = FALSE)
BiocManager::install("ggprism", update = FALSE)
BiocManager::install("mixOmicsTeam/mixOmics", update = FALSE)
BiocManager::install("ISOpureR", update = FALSE)
BiocManager::install("utilities", update = FALSE)
BiocManager::install("SNFtool", update = FALSE)
BiocManager::install("CancerSubtypes", update = FALSE)
BiocManager::install("pamr", update = FALSE)
BiocManager::install("ggvenn", update = FALSE)
BiocManager::install("Rediscover", update = FALSE)
BiocManager::install("gglayer", update = FALSE)
BiocManager::install("PupillometryR", update = FALSE)
BiocManager::install("factoextra", update = FALSE)
BiocManager::install("berryFunctions", update = FALSE)
BiocManager::install("dendsort", update = FALSE)
BiocManager::install("meme", update = FALSE)
BiocManager::install("nomogramEx", update = FALSE)
BiocManager::install("tab", update = FALSE)
BiocManager::install("depmap", update = FALSE)
BiocManager::install("dr4pl", update = FALSE)
BiocManager::install("hdf5r", update = FALSE)
BiocManager::install("recount", update = FALSE)
BiocManager::install("geosphere", update = FALSE)
BiocManager::install("DEP", update = FALSE)
BiocManager::install("splitstackshape", update = FALSE)
BiocManager::install("dplyr", update = FALSE)
BiocManager::install("UpSetR", update = FALSE)
BiocManager::install("AnnoProbe", update = FALSE)
BiocManager::install("ggh4x", update = FALSE)
BiocManager::install("EnhancedVolcano", update = FALSE)
BiocManager::install("M3C", update = FALSE)
BiocManager::install("mygene", update = FALSE)
BiocManager::install("UniProt.ws", update = FALSE)
BiocManager::install("regioneR", update = FALSE)
BiocManager::install("ChAMPdata", update = FALSE,force = TRUE)
BiocManager::install("mosaic", update = FALSE)
BiocManager::install("ggrisk", update = FALSE)
BiocManager::install("harmony", update = FALSE)
BiocManager::install("SCINA", update = FALSE)
BiocManager::install("Orthology.eg.db", update = FALSE)
BiocManager::install("jsonlite", update = FALSE)
BiocManager::install("rlang", update = FALSE)
BiocManager::install("bladderbatch", update = FALSE)
BiocManager::install("randomcoloR", update = FALSE)
BiocManager::install("monocle", update = FALSE)
BiocManager::install("densvis", update = FALSE)
BiocManager::install("plger/scDblFinder",update = FALSE)
BiocManager::install("SC3", update = FALSE)
BiocManager::install("EnsDb.Hsapiens.v86", update = FALSE)
BiocManager::install("simplifyEnrichment", update = FALSE)


# GitHub安装#######
devtools::install_version("survival", version = "3.6.4", repos = "http://cran.us.r-project.org")

devtools::install_github("",upgrade = "never")
devtools::install_github("rlbarter/superheat",upgrade = "never")
devtools::install_github("cran/NADIA",upgrade = "never")
devtools::install_github("mlr-org/mlr3proba",upgrade = "never")
remotes::install_url('https://github.com/catboost/catboost/releases/download/v1.2.7/catboost-R-linux-aarch64-1.2.7.tgz', INSTALL_opts = c("--no-multiarch", "--no-test-load"))
devtools::install_github("mlr-org/mlr3extralearners@*release",upgrade = "never")
devtools::install_github("mlr3learners/mlr3learners.lightgbm",upgrade = "never")
devtools::install_github("mlr3learners/mlr3learners.randomforest",upgrade = "never")
devtools::install_github("yikeshu0611/cutoff",upgrade = "never")
devtools::install_github("kunhuo/plotRCS",upgrade = "never")
devtools::install_github("NightingaleHealth/ggforestplot",upgrade = "never")
devtools::install_github("isubirana/compareGroups",upgrade = "never")
devtools::install_github("mlr-org/bbotk",upgrade = "never")
devtools::install_github("mlr-org/mlr3tuning",upgrade = "never")
devtools::install_github("mlr-org/paradox",upgrade = "never")
devtools::install_github("Rdatatable/data.table",upgrade = "never")
devtools::install_github("cran/lightgbm",upgrade = "never")
devtools::install_github("binderh/CoxBoost",upgrade = "never")
devtools::install_github("hrbrmstr/ggalt",upgrade = "never")
devtools::install_github("davidsjoberg/ggsankey",upgrade = "never") # 桑基图
devtools::install_github("junjunlab/GseaVis",upgrade = "never")
devtools::install_github("zqfang/MuDataSeurat",upgrade = "never")
devtools::install_github("mojaveazure/seurat-disk",upgrade = "never")
devtools::install_github("JiekaiLab/dior",upgrade = "never")
devtools::install_github("sunduanchen/Scissor",upgrade = "never")
devtools::install_github("cellgeni/sceasy",upgrade = "never")
devtools::install_github("Japrin/sscVis",upgrade = "never")
devtools::install_github("cttobin/ggthemr",upgrade = "never")
devtools::install_github("xu-lab/CellRef",upgrade = "never")
devtools::install_github("satijalab/seurat-data",upgrade = "never")
devtools::install_github("mrcieu/ieugwasr",upgrade = "never")
devtools::install_github("jakesherman/easypackages",upgrade = "never")
devtools::install_github("ggjlab/scHCL",upgrade = "never")
devtools::install_github("ropensci/jsonvalidate",upgrade = "never")
devtools::install_github("LTLA/celldex",upgrade = "never")
devtools::install_github("PaulingLiu/scibet",upgrade = "never")
devtools::install_github("WSpiller/MVMR",upgrade = "never")
devtools::install_github("IOstrovnaya/Clonality",upgrade = "never")
devtools::install_github("victoraLab/clonality",upgrade = "never")
devtools::install_github("sinarueeger/GWAS.utils",upgrade = "never")
devtools::install_github("explodecomputer/plinkbinr",upgrade = "never")
devtools::install_github("mrcieu/gwasglue",upgrade = "never")
devtools::install_github("aertslab/SCENIC",upgrade = "never")
devtools::install_github("aertslab/SCopeLoomR",upgrade = "never")
devtools::install_github("junjunlab/scRNAtoolVis",upgrade = "never")
devtools::install_github("junjunlab/ClusterGVis",upgrade = "never")
devtools::install_github("neurorestore/Libra",upgrade = "never")
devtools::install_github("rondolab/MR-PRESSO",upgrade = "never")
devtools::install_github("MRCIEU/TwoSampleMR",upgrade = "never")
devtools::install_github("elliefewings/DoMultiBarHeatmap",upgrade = "never")
devtools::install_github("saeyslab/nichenetr",upgrade = "never")
devtools::install_github("Coolgenome/iTALK",upgrade = "never")
devtools::install_github("cole-trapnell-lab/monocle3",upgrade = "never")
devtools::install_github("PoisonAlien/TCGAmutations",upgrade = "never")
devtools::install_github("mskcc/pctGCdata",upgrade = "never")
devtools::install_github("mskcc/facets",upgrade = "never")
devtools::install_github("aertslab/SCENIC",upgrade = "never")
devtools::install_github("hhoeflin/hdf5r",upgrade = "never")
devtools::install_github(c("chris-mcginnis-ucsf/DoubletFinder","mojaveazure/loomR"),upgrade = "never")
devtools::install_github("TheHumphreysLab/plot1cell",upgrade = "never")
remotes::install_github("lindeloev/job")
remotes::install_github("jokergoo/InteractiveComplexHeatmap")
devtools::install_github('satijalab/seurat-data')
devtools::install_github("saezlab/progeny")
remotes::install_github("federicomarini/quantiseqr", 
                        dependencies = TRUE, build_vignettes = TRUE)
remotes::install_github("JamesHWade/gpttools")
remotes::install_github("lydiaMyr/ImmuCellAI@main")
devtools::install_github("jmzeng1314/idmap1")
devtools::install_github("jmzeng1314/idmap2")
devtools::install_github("gaospecial/ggVennDiagram")
devtools::install_github("talgalili/d3heatmap",upgrade = "never")
remotes::install_github("tanaylab/tgutil",upgrade = "never")
remotes::install_github("RRHO2/RRHO2", build_opts = c("--no-resave-data", "--no-manual"),upgrade = "never")
remotes::install_github("GuangchuangYu/yyplot",upgrade = "never")
remotes::install_github("IndrajeetPatil/pairwiseComparisons",upgrade = "never")
remotes::install_github("lijian13/rinds",upgrade = "never")
devtools::install_github("strengejacke/sjPlot",upgrade = "never")
remotes::install_github("gastonstat/plspm",upgrade = "never")
remotes::install_github("emwozniak/Table1",upgrade = "never")
devtools::install_github("GuangchuangYu/yyplot",upgrade = "never")
devtools::install_github('fawda123/ggord',upgrade = "never")
devtools::install_github("kassambara/factoextra",upgrade = "never")
devtools::install_github("todaroroad/AnnoProbe",upgrade = "never")
devtools::install_git("https://gitee.com/ct5869/ImageGP",upgrade = "never")
devtools::install_github("zzwch/crosslinks",upgrade = "never")
source("http://www.rforge.net/NCStats/InstallNCStats.R",upgrade = "never")
remotes::install_github("courtiol/lay",upgrade = "never")
remotes::install_github("omnideconv/immunedeconv",upgrade = "never")
devtools::install_github("todaroroad/ggcor_0.9.8.1",upgrade = "never")
devtools::install_github("xjsun1221/tinyarray",upgrade = "never")
devtools::install_github("YuLab-SMU/GOSemSim",upgrade = "never")
devtools::install_github("YuLab-SMU/DOSE",upgrade = "never")
devtools::install_github("YuLab-SMU/clusterProfiler",upgrade = "never")
devtools::install_github("IRkernel/IRkernel",upgrade = "never")
devtools::install_github("YuanTian1991/ChAMP",upgrade = "never")
remotes::install_github('YuLab-SMU/ggtree')
devtools::install_github("YuanTian1991/ChAMPdata",upgrade = "never") # 太大了下载不小来报错
devtools::install_github("PYangLab/PhosR")
devtools::install_github("todaroroad/IMvigor210CoreBiologies",upgrade = "never")
devtools::install_github("navinlabcode/copykat",upgrade = "never")
devtools::install_github("IOBR/IOBR",upgrade = "never")
devtools::install_github("GuangchuangYu/gglayer",upgrade = "never")
devtools::install_github('fawda123/ggord',upgrade = "never")
devtools::install_github("sqjin/CellChat",upgrade = "never")


# 安装指定版本R
remove.packages("rlang")
remotes::install_version("rlang", version = "1.1.3")


